config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: "home#index"
  root to: "home#index"
  resources :branches
  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
    #has_many :employees
    validates :branch_name, presence: true, uniqueness: true
    validates :colony_name, presence: true
    validates :country, presence: true, format: { with: /^[a-zA-Z\d ]*$/i, message: "only allows letters" }
    validates :state, presence: true
    validates :ext_num, numericality: { only_integer: true }
    validates :int_num, numericality: { only_integer: true }
    validates :zip_code, presence: true, numericality: { only_integer: true }, length:  { is: 5 }
end

app/models/employee.rb
class Employee < ApplicationRecord
    #belongs_to :branches
    validates :employee_name, presence: true
    validates :rfc, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validate :rfc, uniqueness: true
  validate :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :rfc, :company])
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
    def index
        @branches = Branch.all
    end

    def new
        @branch = Branch.new
    end

    def show
        @branch = Branch.find(params[:id])
    end

    def create
        @branch = Branch.new(branch_params)
        if(@branch.save)
            redirect_to @branch
        else
            render 'new'
        end
    end

    def edit
        @branch = Branch.find(params[:id])
    end

    def update
        @branch = Branch.find(params[:id])
        if(@branch.update(branch_params))
            redirect_to @branch
        else
            render 'edit'
        end
    end

    def destroy
        @branch = Branch.find(params[:id])
        @branch.destroy

        redirect_to branches_path
    end

    private def branch_params
        params.require(:branch).permit(:branch_name, :street_name, :colony_name, :country, :state, :ext_num, :int_num, :zip_code)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    def index
        @employees = Employee.all
    end

    def new
        @employee = Employee.new
    end

    def show
        @employee = Employee.find(params[:id])
    end

    def create
        @employee = Employee.new(employee_params)
        if(@employee.save)
            redirect_to @employee
        else
            render 'new'
        end
    end

    def edit
        @employee = Employee.find(params[:id])
    end

    def update
        @employee = Employee.find(params[:id])
        if(@employee.update(employee_params))
            redirect_to @employee
        else
            render 'edit'
        end
    end

    def destroy
        @employee = Employee.find(params[:id])
        @employee.destroy
        redirect_to employees_path
    end

    private def employee_params
        params.require(:employee).permit(:employee_name, :branch_name, :rfc, :position)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branch_office_helper.rb
module BranchOfficeHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/branches/edit.html.erb
<div class="container">
<%= form_for :branch, url: branch_path(@branch), method: :patch do |f| %>
    <p>
        <%= f.label :sucursal %><br>
        <%= f.text_field(:branch_name, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.label :calle %><br>
        <%= f.text_field(:street_name, {:class => 'form-control'})  %>
    </p>
    <p>
        <%= f.label :colonia %><br>
        <%= f.text_field(:colony_name, {:class => 'form-control'})  %>
    </p>
    <p>
        <%= f.label :cuidad %><br>
        <%= f.text_field(:country, {:class => 'form-control'})  %>
    </p>
    <p>
        <%= f.label :estado %><br>
        <%= f.text_field(:state, {:class => 'form-control'})  %>
    </p>
    <p>
        <%= f.label :num_ext %><br>
        <%= f.text_field(:ext_num, {:class => 'form-control'})  %>
    </p>
    <p>
        <%= f.label :num_int %><br>
        <%= f.text_field(:int_num, {:class => 'form-control'})  %>
    </p>
    <p>
        <%= f.label :codigo_postal %><br>
        <%= f.text_field(:zip_code, {:class => 'form-control'})  %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>
</div>

app/views/branches/index.html.erb
<h1>Lista de sucursales</h1>
<div class="container">
<table style="width:100%">
<% if @branches.empty?%>
    <h1>No hay Sucursales</h1>
<% else %>
<tr>
<th>Nombre de la sucursales</th>
<th>Calle</th>
<th>Colonia</th>
<th>Pais</th>
<th>Estado</th>
<th>Num.Ext</th>
<th>Num.Int</th>
<th>Codigo Postal</th>
<th>Editar</th>
</tr>
</table>
<% @branches.each do |branch| %>
    <div class="well">
        <table style="width:100%">
            <tr>
            <th><%= branch.branch_name %></th>
            <th><%= branch.street_name %></th>
            <th><%= branch.colony_name %></th>
            <th><%= branch.country %></th>
            <th><%= branch.state %></th>
            <th><%= branch.ext_num %></th>
            <th><%= branch.int_num %></th>
            <th><%= branch.zip_code %></th>
            <th><%= link_to "Editar", branch_path(branch), :class => 'btn btn-primary'%></th>
            </tr>
        </table>

    </div>
<% end %>
<% end %>
</div>

app/views/branches/new.html.erb
<div class="container">
<%= form_for @branch, url: branches_path do |f| %>
    <% if @branch.errors.any? %>
        <h3>Errores</h3>
            <ul>
                <% @branch.errors.full_messages.each do |messages| %>
                    <li><%= messages %></li>
                <% end %>
            </ul>
    <% end %>
    <p>
        <%= f.label :sucursal %><br>
        <%= f.text_field(:branch_name, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.label :calle %><br>
        <%= f.text_field(:street_name, {:class => 'form-control'})  %>
    </p>
    <p>
        <%= f.label :colonia %><br>
        <%= f.text_field(:colony_name, {:class => 'form-control'})  %>
    </p>
    <p>
        <%= f.label :ciudad %><br>
        <%= f.text_field(:country, {:class => 'form-control'})  %>
    </p>
    <p>
        <%= f.label :estado %><br>
        <%= f.text_field(:state, {:class => 'form-control'})  %>
    </p>
    <p>
        <%= f.label :num_ext %><br>
        <%= f.text_field(:ext_num, {:class => 'form-control'})  %>
    </p>
    <p>
        <%= f.label :num_int %><br>
        <%= f.text_field(:int_num, {:class => 'form-control'})  %>
    </p>
    <p>
        <%= f.label :codigo_postal %><br>
        <%= f.text_field(:zip_code, {:class => 'form-control'})  %>
    </p>
    <p>
        <%= f.submit ({:class => 'btn btn-primary'})%>
    </p>
<% end %>
</div>

app/views/branches/show.html.erb
<div class="container">
<table style="width:100%">
<tr>
<th>Nombre</th>
<th>Calle</th>
<th>Colonia</th>
<th>Pais</th>
<th>Estado</th>
<th>Num.Ext</th>
<th>Num.Int</th>
<th>Codigo Postal</th>
</tr>
</table>
<table style="width:100%">
            <tr>
            <th><%= @branch.branch_name %></th>
            <th><%= @branch.street_name %></th>
            <th><%= @branch.colony_name %></th>
            <th><%= @branch.country %></th>
            <th><%= @branch.state %></th>
            <th><%= @branch.ext_num %></th>
            <th><%= @branch.int_num %></th>
            <th><%= @branch.zip_code %></th>
            <th><%= link_to "Editar", edit_branch_path(@branch), :class => 'btn btn-default' %></th>
            <th><%= link_to "Borrar", branch_path(@branch), method: :delete,
                                            data: {confirm: 'Estas Seguro?'},
                                            :class => 'btn btn-danger' %></th>
</div>

app/views/employees/edit.html.erb
<div class="container">
<%= form_for :employee, url: employee_path(@employee), method: :patch do |f| %>
    <p>
        <%= f.label :employee_name %><br>
        <%= f.text_field(:employee_name, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.label :branch_name %>
        <%= f.collection_select :branch_name, Branch.all, :branch_name, :branch_name %>
    </p>
    <p>
        <%= f.label :rfc %><br>
        <%= f.text_field(:rfc, {:class => 'form-control', :readonly => true})  %>
    </p>
    <p>
        <%= f.label :position %><br>
        <%= f.text_field(:position, {:class => 'form-control'})  %>
    </p>
    <p>
        <%= f.submit ({:class => 'btn btn-primary'})%>
    </p>
<% end %>
</div>

app/views/employees/index.html.erb
<h1>Lista de Empleados</h1>
<div class="container">
<table style="width:100%">
<tr>
<th>Nombre de los Empleados</th>
<th>Nombre</th>
<th>Nombre de la Sucursal</th>
<th>RFC</th>
<th>Puesto</th>
<th>Editar</th>
</tr>
</table>
<% @employees.each do |employee| %>
    <div class="well">
    <table style="width:100%">
        <tr>
        <th><%= employee.employee_name %></th>
        <th><%= employee.branch_name %></th>
        <th><%= employee.rfc %></th>
        <th><%= employee.position %></th>
        <th><%= link_to "Edit", employee_path(employee), :class => 'btn btn-primary'%></th>
        </tr>
        </table>
    </div>
<% end %>
</div>

app/views/employees/new.html.erb
<div class="container">
<%= form_for @employee, url: employees_path do |f| %>
    <% if @employee.errors.any? %>
        <h3>Errores</h3>
            <ul>
                <% @employee.errors.full_messages.each do |messages| %>
                    <li><%= messages %></li>
                <% end %>
            </ul>
    <% end %>
    <p>
        <%= f.label :employee_name %><br>
        <%= f.text_field(:employee_name, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.label :branch_name %>
        <%= f.collection_select :branch_name, Branch.all, :branch_name, :branch_name %>
    </p>
    <p>
        <%= f.label :rfc %><br>
        <%= f.text_field(:rfc, {:class => 'form-control'})  %>
    </p>
    <p>
        <%= f.label :position %><br>
        <%= f.text_field(:position, {:class => 'form-control'})  %>
    </p>
    <p>
        <%= f.submit ({:class => 'btn btn-primary'})%>
    </p>
<% end %>
</div>

app/views/employees/show.html.erb
<div class="container">
<table style="width:100%">
<tr>
<th>Nombre de los Empleados</th>
<th>Nombre</th>
<th>Sucursal</th>
<th>RFC</th>
<th>Puesto</th>
</tr>
</table>
<table style="width:100%">
<tr>
<th><%= @employee.employee_name %></th>
<th><%= @employee.branch_name %></th>
<th><%= @employee.rfc %></th>
<th><%= @employee.position %></th>
<th><%= link_to "Edit", edit_employee_path(@employee), :class => 'btn btn-default' %></th>
<th><%= link_to "Delete", employee_path(@employee), method: :delete,
                                            data: {confirm: 'Estas Seguro?'},
                                            :class => 'btn btn-danger' %></th>
</tr>
</table>
</div>

app/views/home/index.html.erb
<% name = current_user.present? ? current_user.email : 'Stranger' %>

<h1>Welcome, <%=name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">CodeTest</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link'%>
    </li>
    <li class="nav-item">
      <%= link_to 'Ver Sucursales', branches_path, class: 'nav-link'%>
    </li>
    <li class="nav-item">
      <%= link_to 'Crear Sucursal', new_branch_path, class: 'nav-link'%>
    </li>
    <li class="nav-item">
      <%= link_to 'Ver Empleados', employees_path, class: 'nav-link'%>
    </li>
    <li class="nav-item">
      <%= link_to 'Crear Empleados', new_employee_path, class: 'nav-link'%>
    </li>
    <% else %>
    <li class="nav-item">
      <%= link_to 'Register', new_user_registration_path, class: 'nav-link'%>
    </li>
    <li class="nav-item">
      <%= link_to 'Sign in', new_user_session_path, class: 'nav-link'%>
    </li>
    <% end %>
    </ul>
  </div>
</nav>